// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poisonpill.proto

#ifndef PROTOBUF_INCLUDED_poisonpill_2eproto
#define PROTOBUF_INCLUDED_poisonpill_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_poisonpill_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_poisonpill_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_poisonpill_2eproto();
class PoisonPill;
class PoisonPillDefaultTypeInternal;
extern PoisonPillDefaultTypeInternal _PoisonPill_default_instance_;
namespace google {
namespace protobuf {
template<> ::PoisonPill* Arena::CreateMaybeMessage<::PoisonPill>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class PoisonPill :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PoisonPill) */ {
 public:
  PoisonPill();
  virtual ~PoisonPill();

  PoisonPill(const PoisonPill& from);

  inline PoisonPill& operator=(const PoisonPill& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PoisonPill(PoisonPill&& from) noexcept
    : PoisonPill() {
    *this = ::std::move(from);
  }

  inline PoisonPill& operator=(PoisonPill&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PoisonPill& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PoisonPill* internal_default_instance() {
    return reinterpret_cast<const PoisonPill*>(
               &_PoisonPill_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PoisonPill* other);
  friend void swap(PoisonPill& a, PoisonPill& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PoisonPill* New() const final {
    return CreateMaybeMessage<PoisonPill>(nullptr);
  }

  PoisonPill* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PoisonPill>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PoisonPill& from);
  void MergeFrom(const PoisonPill& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PoisonPill* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string pill = 1;
  void clear_pill();
  static const int kPillFieldNumber = 1;
  const ::std::string& pill() const;
  void set_pill(const ::std::string& value);
  #if LANG_CXX11
  void set_pill(::std::string&& value);
  #endif
  void set_pill(const char* value);
  void set_pill(const char* value, size_t size);
  ::std::string* mutable_pill();
  ::std::string* release_pill();
  void set_allocated_pill(::std::string* pill);

  // @@protoc_insertion_point(class_scope:PoisonPill)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr pill_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_poisonpill_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PoisonPill

// string pill = 1;
inline void PoisonPill::clear_pill() {
  pill_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PoisonPill::pill() const {
  // @@protoc_insertion_point(field_get:PoisonPill.pill)
  return pill_.GetNoArena();
}
inline void PoisonPill::set_pill(const ::std::string& value) {
  
  pill_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PoisonPill.pill)
}
#if LANG_CXX11
inline void PoisonPill::set_pill(::std::string&& value) {
  
  pill_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PoisonPill.pill)
}
#endif
inline void PoisonPill::set_pill(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pill_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PoisonPill.pill)
}
inline void PoisonPill::set_pill(const char* value, size_t size) {
  
  pill_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PoisonPill.pill)
}
inline ::std::string* PoisonPill::mutable_pill() {
  
  // @@protoc_insertion_point(field_mutable:PoisonPill.pill)
  return pill_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PoisonPill::release_pill() {
  // @@protoc_insertion_point(field_release:PoisonPill.pill)
  
  return pill_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PoisonPill::set_allocated_pill(::std::string* pill) {
  if (pill != nullptr) {
    
  } else {
    
  }
  pill_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pill);
  // @@protoc_insertion_point(field_set_allocated:PoisonPill.pill)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_poisonpill_2eproto
