// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poisonpill.proto

#include "poisonpill.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

class PoisonPillDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PoisonPill> _instance;
} _PoisonPill_default_instance_;
static void InitDefaultsPoisonPill_poisonpill_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PoisonPill_default_instance_;
    new (ptr) ::PoisonPill();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PoisonPill::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PoisonPill_poisonpill_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPoisonPill_poisonpill_2eproto}, {}};

void InitDefaults_poisonpill_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_PoisonPill_poisonpill_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_poisonpill_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_poisonpill_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_poisonpill_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_poisonpill_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PoisonPill, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PoisonPill, pill_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PoisonPill)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PoisonPill_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_poisonpill_2eproto = {
  {}, AddDescriptors_poisonpill_2eproto, "poisonpill.proto", schemas,
  file_default_instances, TableStruct_poisonpill_2eproto::offsets,
  file_level_metadata_poisonpill_2eproto, 1, file_level_enum_descriptors_poisonpill_2eproto, file_level_service_descriptors_poisonpill_2eproto,
};

const char descriptor_table_protodef_poisonpill_2eproto[] =
  "\n\020poisonpill.proto\"\032\n\nPoisonPill\022\014\n\004pill"
  "\030\001 \001(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_poisonpill_2eproto = {
  false, InitDefaults_poisonpill_2eproto, 
  descriptor_table_protodef_poisonpill_2eproto,
  "poisonpill.proto", &assign_descriptors_table_poisonpill_2eproto, 54,
};

void AddDescriptors_poisonpill_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_poisonpill_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_poisonpill_2eproto = []() { AddDescriptors_poisonpill_2eproto(); return true; }();

// ===================================================================

void PoisonPill::InitAsDefaultInstance() {
}
class PoisonPill::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PoisonPill::kPillFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PoisonPill::PoisonPill()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PoisonPill)
}
PoisonPill::PoisonPill(const PoisonPill& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pill_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.pill().size() > 0) {
    pill_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pill_);
  }
  // @@protoc_insertion_point(copy_constructor:PoisonPill)
}

void PoisonPill::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_PoisonPill_poisonpill_2eproto.base);
  pill_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PoisonPill::~PoisonPill() {
  // @@protoc_insertion_point(destructor:PoisonPill)
  SharedDtor();
}

void PoisonPill::SharedDtor() {
  pill_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PoisonPill::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PoisonPill& PoisonPill::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_PoisonPill_poisonpill_2eproto.base);
  return *internal_default_instance();
}


void PoisonPill::Clear() {
// @@protoc_insertion_point(message_clear_start:PoisonPill)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pill_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* PoisonPill::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<PoisonPill*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string pill = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("PoisonPill.pill");
        object = msg->mutable_pill();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool PoisonPill::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PoisonPill)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string pill = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pill()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pill().data(), static_cast<int>(this->pill().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PoisonPill.pill"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PoisonPill)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PoisonPill)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void PoisonPill::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PoisonPill)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string pill = 1;
  if (this->pill().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pill().data(), static_cast<int>(this->pill().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PoisonPill.pill");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->pill(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PoisonPill)
}

::google::protobuf::uint8* PoisonPill::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PoisonPill)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string pill = 1;
  if (this->pill().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pill().data(), static_cast<int>(this->pill().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PoisonPill.pill");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->pill(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PoisonPill)
  return target;
}

size_t PoisonPill::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PoisonPill)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pill = 1;
  if (this->pill().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pill());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PoisonPill::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PoisonPill)
  GOOGLE_DCHECK_NE(&from, this);
  const PoisonPill* source =
      ::google::protobuf::DynamicCastToGenerated<PoisonPill>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PoisonPill)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PoisonPill)
    MergeFrom(*source);
  }
}

void PoisonPill::MergeFrom(const PoisonPill& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PoisonPill)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pill().size() > 0) {

    pill_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pill_);
  }
}

void PoisonPill::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PoisonPill)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PoisonPill::CopyFrom(const PoisonPill& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PoisonPill)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PoisonPill::IsInitialized() const {
  return true;
}

void PoisonPill::Swap(PoisonPill* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PoisonPill::InternalSwap(PoisonPill* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  pill_.Swap(&other->pill_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata PoisonPill::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_poisonpill_2eproto);
  return ::file_level_metadata_poisonpill_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::PoisonPill* Arena::CreateMaybeMessage< ::PoisonPill >(Arena* arena) {
  return Arena::CreateInternal< ::PoisonPill >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
